namespace TDesu.Telegram.TL.Generator

open System.IO

/// Naming + hygiene primitives shared by every file emitter: the extension
/// downstream code sees (`.g.fs`), the banner that consumers see at
/// the top of every file, and the marker line that lets the tool safely
/// wipe its own output without touching hand-added files in the same dir.
///
/// One source of truth so every emitter writes the same shape — a downstream
/// grep for `//# td-tl-gen-managed` finds every file this tool produced.
module Managed =

    /// Extension used for every emitted F# file. Matches Roslyn's `.g.cs`
    /// convention that td-tl-gen has always used. (`.Generated.fs` was
    /// briefly tried in 0.10.0-alpha.1 for Myriad consistency but reverted
    /// in alpha.2 — the churn on every downstream fsproj wasn't worth the
    /// cosmetic gain, and the marker below already lets safe-wipe scope
    /// correctly regardless of extension.)
    let Ext = ".g.fs"

    /// Machine-detectable marker written on line 6 of every managed file.
    /// Deliberately terse and unlikely to appear elsewhere; the safe-wipe
    /// grep-matches on this exact string.
    [<Literal>]
    let Marker = "//# td-tl-gen-managed"

    /// F# comment banner + marker for emitted files. `regenHint` is the exact
    /// CLI invocation the downstream tree uses to rebuild — quoted verbatim
    /// so a reader can copy-paste it. The `<auto-generated>` XML comment is
    /// the canonical marker that Fantomas, Roslyn analyzers, IDE lints, and
    /// StyleCop all skip warnings on.
    let banner (regenHint: string) : string =
        let lines = [
            "// <auto-generated>"
            "//   This file is generated by td-tl-gen from a TL schema + overrides."
            "//   DO NOT EDIT — the next regen overwrites your changes."
            $"//   Rebuild: {regenHint}"
            "// </auto-generated>"
            Marker
            ""
        ]
        System.String.Join("\n", lines) + "\n"

    /// XML variant of the banner for `.targets` manifests. Same marker so
    /// the safe-wipe catches manifest files too. XML comments forbid `--`
    /// inside the body — `regenHint` is deliberately abstracted to a tool
    /// name only to keep double-dashes out of the payload.
    let xmlBanner (toolName: string) : string =
        "<!-- <auto-generated>\n"
        + "     " + toolName + " output. Regenerated by the tool; do not edit.\n"
        + "     " + Marker + "\n"
        + "-->\n"

    /// True when the first 10 lines of `path` contain our marker. Cheap: the
    /// marker sits on line 6 of every managed file, so a bail-out at 10 lines
    /// avoids reading whole megabyte-sized types files.
    let isManagedFile (path: string) : bool =
        try
            use reader = new StreamReader(path)
            let mutable line = reader.ReadLine()
            let mutable seen = 0
            let mutable found = false

            while not found && line <> null && seen < 10 do
                if line.StartsWith Marker then found <- true
                else
                    line <- reader.ReadLine()
                    seen <- seen + 1

            found
        with _ ->
            false

    /// Delete every file in `dir` that carries our marker. Sweeps both the
    /// current `.g.fs` extension and the `.Generated.fs` extension used
    /// briefly in 0.10.0-alpha.1 (kept so an alpha.1 → alpha.2 downgrade
    /// cleans up).
    /// Hand-added `.fs` without the marker survives.
    ///
    /// Also targets `*.targets` XML manifests, matched by the same marker.
    let sweep (dir: string) =
        if Directory.Exists dir then
            for pattern in [ "*.g.fs"; "*.Generated.fs"; "*.targets" ] do
                for f in Directory.EnumerateFiles(dir, pattern, SearchOption.AllDirectories) do
                    if isManagedFile f then File.Delete f

    /// Compose `directory` and `basename` into a full managed-file path.
    /// `basename` is the leaf without extension (e.g. "Base", "GeneratedCid").
    let outputPath (directory: string) (basename: string) : string =
        Path.Combine(directory, basename + Ext)
