namespace TDesu.Telegram.TL.Generator

open System.IO

/// Naming + hygiene primitives shared by every file emitter: the extension
/// downstream code sees (`.Generated.fs`), the banner that consumers see at
/// the top of every file, and the marker line that lets the tool safely
/// wipe its own output without touching hand-added files in the same dir.
///
/// One source of truth so every emitter writes the same shape — a downstream
/// grep for `//# td-tl-gen-managed` finds every file this tool produced.
module Managed =

    /// Extension used for every emitted F# file. Consistent with the wider
    /// .NET source-generator convention (`*.Generated.cs`, Myriad's
    /// `*LogDef.Generated.fs`); the earlier `.g.fs` was a td-tl-gen-ism
    /// inherited from Roslyn's `.g.cs`.
    [<Literal>]
    let Ext = ".Generated.fs"

    /// Machine-detectable marker written on line 6 of every managed file.
    /// Deliberately terse and unlikely to appear elsewhere; the safe-wipe
    /// grep-matches on this exact string.
    [<Literal>]
    let Marker = "//# td-tl-gen-managed"

    /// F# comment banner + marker for `.Generated.fs` files. `regenHint` is
    /// the exact CLI invocation the downstream tree uses to rebuild — quoted
    /// verbatim so a reader can copy-paste it. The `<auto-generated>` XML
    /// comment is the canonical marker that Fantomas, Roslyn analyzers, IDE
    /// lints, and StyleCop all skip warnings on.
    let banner (regenHint: string) : string =
        let lines = [
            "// <auto-generated>"
            "//   This file is generated by td-tl-gen from a TL schema + overrides."
            "//   DO NOT EDIT — the next regen overwrites your changes."
            $"//   Rebuild: {regenHint}"
            "// </auto-generated>"
            Marker
            ""
        ]
        System.String.Join("\n", lines) + "\n"

    /// XML variant of the banner for `.targets` manifests. Same marker so the
    /// safe-wipe catches manifest files too.
    /// XML variant of the banner for `.targets` manifests. Same marker so
    /// the safe-wipe catches manifest files too. XML comments forbid `--`
    /// inside the body — the caller MUST NOT pass a hint with double dashes,
    /// so `regenHint` here is deliberately abstracted to a tool name only.
    let xmlBanner (toolName: string) : string =
        "<!-- <auto-generated>\n"
        + "     " + toolName + " output. Regenerated by the tool; do not edit.\n"
        + "     " + Marker + "\n"
        + "-->\n"

    /// True when the first 10 lines of `path` contain our marker. Cheap: the
    /// marker sits on line 6 of every managed file, so a bail-out at 10 lines
    /// avoids reading whole megabyte-sized types files.
    let isManagedFile (path: string) : bool =
        try
            use reader = new StreamReader(path)
            let mutable line = reader.ReadLine()
            let mutable seen = 0
            let mutable found = false

            while not found && line <> null && seen < 10 do
                if line.StartsWith Marker then found <- true
                else
                    line <- reader.ReadLine()
                    seen <- seen + 1

            found
        with _ ->
            false

    /// Delete every file in `dir` that WE wrote (marker present) plus any
    /// legacy `.g.fs` (which never had a marker but which we know belong to
    /// the previous emitter incarnation). Hand-added `.fs` files without the
    /// marker survive.
    ///
    /// `patterns` is the set of glob patterns to check for the marker; the
    /// legacy `.g.fs` sweep is unconditional (safe: the tool NEVER produced
    /// a `.g.fs` anyone else would want to keep in its output dir). Also
    /// targets `*.targets` XML manifests.
    let sweep (dir: string) =
        if Directory.Exists dir then
            // Legacy: pre-.Generated.fs output. Nothing else has ever lived
            // in the tool's output dir with this extension.
            for f in Directory.EnumerateFiles(dir, "*.g.fs", SearchOption.AllDirectories) do
                File.Delete f

            // Managed: matched by marker so a user's hand-added file survives.
            for f in Directory.EnumerateFiles(dir, "*" + Ext, SearchOption.AllDirectories) do
                if isManagedFile f then File.Delete f

            for f in Directory.EnumerateFiles(dir, "*.targets", SearchOption.AllDirectories) do
                if isManagedFile f then File.Delete f

    /// Compose `directory` and `basename` into a full managed-file path.
    /// `basename` is the leaf without extension (e.g. "Base", "GeneratedCid").
    let outputPath (directory: string) (basename: string) : string =
        Path.Combine(directory, basename + Ext)
