// Regenerate the mtproto.tl service layer used by TDesu.Telegram.Protocol.
//
// The client used to hand-write every service constructor: literal ids, a literal vector id, a
// length and a loop, per message type. That is how a schema change becomes a silent wire bug
// instead of a compile error, and it is why this exists.
//
//   dotnet fsi tools/regen-mtproto.fsx           regenerate
//   dotnet fsi tools/regen-mtproto.fsx --check   fail if the tree is stale
//
// Whitelisted rather than --no-whitelist deliberately: mtproto.tl declares a function
// `rpc_drop_answer` whose return type is also `RpcDropAnswer`, and the emitter gives both the same
// F# name, so the full schema does not compile. See src/tl-overrides/mtproto.toml.

open System
open System.Diagnostics
open System.IO
open System.Security.Cryptography

let repoRoot =
    let rec walk (dir: DirectoryInfo) =
        if isNull dir then failwith "no repository root above this script"
        elif Directory.Exists(Path.Combine(dir.FullName, ".git")) then dir.FullName
        else walk dir.Parent

    walk (DirectoryInfo __SOURCE_DIRECTORY__)

let schema = Path.Combine(repoRoot, "cached", "mtproto.tl")
let overrides = Path.Combine(repoRoot, "src", "tl-overrides", "mtproto.toml")
let generator = Path.Combine(repoRoot, "src", "TDesu.Telegram.TL.Generator")
let outputDir = Path.Combine(repoRoot, "src", "TDesu.Telegram.Protocol", "Generated")
let lockPath = Path.Combine(outputDir, "regen.lock")
let ns = "TDesu.MTProto.Service"
let targets = "cid,types"

/// Hashed LF-normalized so a checkout with CRLF does not read as a change.
let hashFile (path: string) =
    let bytes = File.ReadAllText(path).Replace("\r\n", "\n") |> Text.Encoding.UTF8.GetBytes
    Convert.ToHexString(SHA256.HashData bytes).ToLowerInvariant()

let expectedLock () =
    String.concat
        "\n"
        [ "# Generated by tools/regen-mtproto.fsx — do not edit."
          $"schema     = {hashFile schema}"
          $"overrides  = {hashFile overrides}"
          $"namespace  = {ns}"
          $"targets    = {targets}" ]
    + "\n"

let run () =
    let psi = ProcessStartInfo("dotnet", RedirectStandardOutput = true, RedirectStandardError = true)

    for a in
        [ "run"
          "--project"
          generator
          "-c"
          "Release"
          "--"
          "--schema"
          schema
          "--mtproto-schema"
          schema
          "--output"
          outputDir
          "--namespace"
          ns
          "--overrides"
          overrides
          "--target"
          targets ] do
        psi.ArgumentList.Add a

    use p = Process.Start psi
    let out = p.StandardOutput.ReadToEnd()
    let err = p.StandardError.ReadToEnd()
    p.WaitForExit()

    if p.ExitCode <> 0 then
        eprintfn "%s%s" out err
        failwith $"td-tl-gen exited {p.ExitCode}"

let isCheck = fsi.CommandLineArgs |> Array.contains "--check"

if isCheck then
    let current = if File.Exists lockPath then File.ReadAllText lockPath else ""

    if current.Replace("\r\n", "\n") = expectedLock () then
        printfn "regen.lock matches"
    else
        eprintfn "regen.lock is stale — run: dotnet fsi tools/regen-mtproto.fsx"
        exit 1
else
    run ()
    File.WriteAllText(lockPath, expectedLock ())
    printfn "Regenerated %s" outputDir
